basePath: /
definitions:
  http.InfoResponse:
    properties:
      name:
        type: string
      version:
        type: string
    type: object
  http.LogStreamResponse:
    properties:
      alias:
        type: string
      id:
        type: string
    type: object
  http.LogStreamWithSecretResponse:
    properties:
      alias:
        type: string
      id:
        type: string
      key:
        type: string
    type: object
  http.LogStreamsResponse:
    properties:
      streams:
        items:
          $ref: '#/definitions/http.LogStreamResponse'
        type: array
    type: object
  http_common.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  http_common.SuccessResponse:
    properties:
      success:
        type: boolean
    type: object
host: localhost:7000
info:
  contact:
    email: contact@fabiankachlock.dev
    name: API Support
  description: this is an example log-rush server
  license:
    name: n.a.
    url: n.a.
  title: log-rush simple server
  version: "1.0"
paths:
  /batch:
    post:
      consumes:
      - application/json
      description: add a bunch of logs at once to a stream
      operationId: batch
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_common.SuccessResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
      summary: push multiple logs at once
      tags:
      - log
  /info:
    get:
      description: get all server information
      operationId: info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.InfoResponse'
      summary: get the server info
      tags:
      - system
  /log:
    post:
      consumes:
      - application/json
      description: add a new log on a logstream
      operationId: log
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_common.SuccessResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
      summary: push a log
      tags:
      - log
  /stream/register:
    post:
      consumes:
      - application/json
      description: create a new logstream on the server so that client can subscribe
        to it
      operationId: register-stream
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.LogStreamWithSecretResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
      summary: register a logstream
      tags:
      - logstream
  /stream/unregister:
    post:
      consumes:
      - application/json
      description: delete a logstream an close all open connection to it
      operationId: unregister-stream
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_common.SuccessResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
      summary: unregister a logstream
      tags:
      - logstream
  /streams:
    get:
      description: get all available logstreams on the server
      operationId: list-stream
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.LogStreamsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
      summary: list all streams
      tags:
      - logstream
  /streams/{id}:
    get:
      description: get info about a logstream
      operationId: get-stream
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.LogStreamResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_common.ErrorResponse'
      summary: fetch a stream
      tags:
      - logstream
swagger: "2.0"
tags:
- description: all endpoints for logstreams
  name: logstream
- description: all endpoints for logs
  name: log
